// components
require('./components/sidebar')
require('./components/datatable')
require('./components/modal-delete')
require('./components/modal-place')
require('./components/modal-client')
require('./components/alert')
require('./components/button')
require('./components/image')
require('./components/tooltip')

// custom
require('./custom/validation')
require('./custom/calculation')
require('./custom/comparison')

// pages
require('./pages/users')
require('./pages/profile')
require('./pages/payments')
require('./pages/statistics')
require('./pages/reports')
// require('./pages/members')
// require('./pages/events')
// require('./pages/passes')
// require('./pages/achievements')
// require('./pages/loads')
// require('./pages/timetable')
// require('./pages/visits')
// require('./pages/support')
// require('./pages/stats')
// require('./pages/reports')
